/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import Entity.NhanVien;
import Form.Bill;
import Form.Product;
import Form.Custom;
import Form.Menu;
import Form.Staff;
import Form.Statistical;
import FormImport.addtable;

import ThuVien.Auth;
import ThuVien.DialogHelper;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.IOException;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 * [689, 551]
 *
 * @author nguyenvanquyet
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    Color Defaultcolor, clickColor;
    int width = 182;
    int height = 595;
    List<NhanVien> listnhanvien = new ArrayList<>();
    LocalDate ngay = LocalDate.now();
    addtable showAddtable;
    Color red = new Color(255, 51, 51);
    Color white = new Color(193, 244, 197);
    int row = -1;

    public Main() {
        initComponents();
//        filltableSanPham();
//        fillcomboboxLoai();
//        filltableHoaDon();
        init();
        setLocationRelativeTo(this);
        Menu men = new Menu();
        panelMainMenu.removeAll();
        panelMainMenu.add(men).setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        myButton1 = new JavaSwingThuVien.MyButton();
        clickMenu = new JavaSwingThuVien.MyButton();
        clickProduct = new JavaSwingThuVien.MyButton();
        clickStatistical = new JavaSwingThuVien.MyButton();
        clickStaff = new JavaSwingThuVien.MyButton();
        ClickCustomer = new JavaSwingThuVien.MyButton();
        myButton2 = new JavaSwingThuVien.MyButton();
        imageAvatar = new ThuVien.ImageAvatar();
        jLabel4 = new javax.swing.JLabel();
        lblChucVu = new javax.swing.JLabel();
        lblTenNV = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelMainMenu = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(103, 93, 80));
        jPanel2.setForeground(new java.awt.Color(255, 153, 102));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Close.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 689, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("QUẢN LÝ QUÁN COFFEE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(367, 367, 367)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(313, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(112, 112, 112)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelMenu.setBackground(new java.awt.Color(103, 93, 80));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        myButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageMain/iconDangXuat.png"))); // NOI18N
        myButton1.setText("ĐĂNG XUẤT");
        myButton1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        myButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        myButton1.setRadius(20);
        myButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                myButton1MousePressed(evt);
            }
        });
        panelMenu.add(myButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, 130, 46));

        clickMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageMain/buttonMenu.png"))); // NOI18N
        clickMenu.setText("MENU");
        clickMenu.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        clickMenu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        clickMenu.setRadius(20);
        clickMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                clickMenuMousePressed(evt);
            }
        });
        panelMenu.add(clickMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 130, 46));

        clickProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageMain/iconSanPham.png"))); // NOI18N
        clickProduct.setText("SẢN PHẨM");
        clickProduct.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        clickProduct.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        clickProduct.setRadius(20);
        clickProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                clickProductMousePressed(evt);
            }
        });
        panelMenu.add(clickProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 130, 46));

        clickStatistical.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageMain/iconThongke.png"))); // NOI18N
        clickStatistical.setText("THỐNG KÊ");
        clickStatistical.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        clickStatistical.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        clickStatistical.setRadius(20);
        clickStatistical.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                clickStatisticalMousePressed(evt);
            }
        });
        panelMenu.add(clickStatistical, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 130, 46));

        clickStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageMain/iconNhanViên.png"))); // NOI18N
        clickStaff.setText("NHÂN VIÊN");
        clickStaff.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        clickStaff.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        clickStaff.setRadius(20);
        clickStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                clickStaffMousePressed(evt);
            }
        });
        panelMenu.add(clickStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 130, 46));

        ClickCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageMain/iconKhachHang.png"))); // NOI18N
        ClickCustomer.setText("KHÁCH HÀNG");
        ClickCustomer.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        ClickCustomer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ClickCustomer.setRadius(20);
        ClickCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClickCustomerMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ClickCustomerMousePressed(evt);
            }
        });
        panelMenu.add(ClickCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 130, 46));

        myButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageMain/iconHoaDon.png"))); // NOI18N
        myButton2.setText("Hóa đơn");
        myButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        myButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        myButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        myButton2.setRadius(20);
        myButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                myButton2MousePressed(evt);
            }
        });
        panelMenu.add(myButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 130, 46));

        imageAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/parkseoJun.jpg"))); // NOI18N
        panelMenu.add(imageAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 0, 140, 120));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Chức vụ:");
        panelMenu.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        lblChucVu.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblChucVu.setForeground(new java.awt.Color(255, 255, 255));
        lblChucVu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChucVu.setText("Quản lý");
        lblChucVu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelMenu.add(lblChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        lblTenNV.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblTenNV.setForeground(new java.awt.Color(255, 255, 255));
        lblTenNV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTenNV.setText("Nguyễn Văn Quyết");
        lblTenNV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelMenu.add(lblTenNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tên:");
        panelMenu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        panelMainMenu.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelMainMenuLayout = new javax.swing.GroupLayout(panelMainMenu);
        panelMainMenu.setLayout(panelMainMenuLayout);
        panelMainMenuLayout.setHorizontalGroup(
            panelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelMainMenuLayout.setVerticalGroup(
            panelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelMainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1151, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void clickProductMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickProductMousePressed
//        clickMenu.setBackground(Defaultcolor);
//        clickBill.setBackground(Defaultcolor);
//        clickProduct.setBackground(clickColor);
//        ClickCustomer.setBackground(Defaultcolor);
//        clickStaff.setBackground(Defaultcolor);
//        clickStatistical.setBackground(Defaultcolor);
        Product product = new Product();
        panelMainMenu.removeAll();
        panelMainMenu.add(product).setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_clickProductMousePressed

    private void clickStatisticalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickStatisticalMousePressed
//        clickMenu.setBackground(Defaultcolor);
//        clickBill.setBackground(Defaultcolor);
//        clickProduct.setBackground(Defaultcolor);
//        ClickCustomer.setBackground(Defaultcolor);
//        clickStaff.setBackground(Defaultcolor);
//        clickStatistical.setBackground(clickColor);
        if (!Auth.isManager()) {
            DialogHelper.alert(this, "Bạn không có quyền vào xem Nhân viên");
        } else {
            Statistical statistical = new Statistical();
            panelMainMenu.removeAll();
            panelMainMenu.add(statistical).setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_clickStatisticalMousePressed

    private void ClickCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClickCustomerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ClickCustomerMouseClicked

    private void ClickCustomerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClickCustomerMousePressed
//        clickMenu.setBackground(Defaultcolor);
//        clickBill.setBackground(Defaultcolor);
//        clickProduct.setBackground(Defaultcolor);
//        ClickCustomer.setBackground(clickColor);
//        clickStaff.setBackground(Defaultcolor);
//        clickStatistical.setBackground(Defaultcolor);

        Custom custom = new Custom();
        panelMainMenu.removeAll();
        panelMainMenu.add(custom).setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_ClickCustomerMousePressed

    private void clickStaffMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickStaffMousePressed
//        clickMenu.setBackground(Defaultcolor);
//        clickBill.setBackground(Defaultcolor);
//        clickProduct.setBackground(Defaultcolor);
//        ClickCustomer.setBackground(Defaultcolor);
//        clickStaff.setBackground(clickColor);
//        clickStatistical.setBackground(Defaultcolor);
        if (!Auth.isManager()) {
            DialogHelper.alert(this, "Bạn không có quyền vào xem Nhân viên");

        } else {
            Staff staff = new Staff();
            panelMainMenu.removeAll();
            panelMainMenu.add(staff).setVisible(true);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_clickStaffMousePressed

    private void myButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myButton1MousePressed
        if (DialogHelper.confirm(this, "Bạn có muốn đăng xuất không")) {
            new FormLogin.Login().setVisible(true);
            this.dispose();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_myButton1MousePressed

    private void clickMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickMenuMousePressed
//        clickMenu.setBackground(clickColor);
//        clickBill.setBackground(Defaultcolor);
//        clickProduct.setBackground(Defaultcolor);
//        ClickCustomer.setBackground(Defaultcolor);
//        clickStaff.setBackground(Defaultcolor);
//        clickStatistical.setBackground(Defaultcolor);
        Menu menu = new Menu();
        // System.out.println("eeeeee");
        panelMainMenu.removeAll();
        panelMainMenu.add(menu).setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_clickMenuMousePressed

    private void myButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myButton2MousePressed
        Bill bill = new Bill();
        panelMainMenu.removeAll();
        panelMainMenu.add(bill).setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_myButton2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JavaSwingThuVien.MyButton ClickCustomer;
    private JavaSwingThuVien.MyButton clickMenu;
    private JavaSwingThuVien.MyButton clickProduct;
    private JavaSwingThuVien.MyButton clickStaff;
    private JavaSwingThuVien.MyButton clickStatistical;
    private ThuVien.ImageAvatar imageAvatar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblChucVu;
    private javax.swing.JLabel lblTenNV;
    private JavaSwingThuVien.MyButton myButton1;
    private JavaSwingThuVien.MyButton myButton2;
    private javax.swing.JPanel panelMainMenu;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables
void init() {
        setLocationRelativeTo(this);
        Defaultcolor = new Color(171, 196, 170);
        clickColor = new Color(255, 255, 255);
        hienthianhlenMain();
    }

    private static byte[] convertIconToByteArray(Icon icon) {
        BufferedImage image = new BufferedImage(icon.getIconWidth(), icon.getIconHeight(), BufferedImage.TYPE_INT_ARGB);
        Graphics g = image.createGraphics();
        icon.paintIcon(null, g, 0, 0);
        g.dispose();
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        try {
            ImageIO.write(image, "png", baos);
        } catch (IOException e) {
            System.out.println(e);
        }
        return baos.toByteArray();
    }
//
    void hienthianhlenMain() {
        ImageIcon icon = new ImageIcon(Auth.user.getHinhanh());
        imageAvatar.setIcon(icon);
        String manv = Auth.user.getTenNV();
        lblTenNV.setText(manv);
        String chucvu = Auth.user.getChucVu() ? "Quản lý" : "Nhân viên";
        lblChucVu.setText(chucvu);
    }

}
