package Form;

import DAO.BanDAO;
import DAO.ChiTietHoaDonDAO;
import DAO.HoaDonDAO;
import DAO.KhachHangDAO;
import DAO.LoaiDAO;
import DAO.SanPhamDAO;
import Entity.Ban;
import Entity.ChiTietHoaDon;
import Entity.HoaDon;
import Entity.KhachHang;
import Entity.Loai;
import Entity.SanPham;
import FormImport.addtable;
import JavaSwingThuVien.MyQuery;
import JavaSwingThuVien.Product2;
import JavaSwingThuVien.TheModel;
import ThuVien.Auth;
import ThuVien.DialogHelper;
import ThuVien.JdbcHelper;
import ThuVien.XDate;
import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nguyenvanquyet
 */
public class Menu extends javax.swing.JInternalFrame {

    /**
     * Creates new form Menu 418,374
     */
    BanDAO daoBan = new BanDAO();
    SanPhamDAO daosp = new SanPhamDAO();
    LoaiDAO daoloai = new LoaiDAO();
    HoaDonDAO daohd = new HoaDonDAO();
    KhachHangDAO daokh = new KhachHangDAO();
    ChiTietHoaDonDAO daohdct = new ChiTietHoaDonDAO();
    LocalDate ngay = LocalDate.now();
    addtable showAddtable;
    Color red = new Color(255, 51, 51);
    Color white = new Color(193, 244, 197);
    int width = 421;
    int height = 374;
    int row = -1;

    public Menu() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        //     fillcomboBoxBan();
        filltableSanPham();
        fillcomboboxLoai();
        filltableHoaDon();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jPanel5 = new javax.swing.JPanel();
        cbxLoai = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableSanPham = new javax.swing.JTable();
        panelHoaDon = new javax.swing.JPanel();
        txtmaHoaDon = new JavaSwingThuVien.TextField();
        txtmaKH = new JavaSwingThuVien.TextField();
        txttenKh = new JavaSwingThuVien.TextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblmaSP = new javax.swing.JLabel();
        lbltenSP = new javax.swing.JLabel();
        lblGia = new javax.swing.JLabel();
        lblLoai = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblthanhTien = new javax.swing.JLabel();
        txtsdt = new JavaSwingThuVien.TextField();
        spinnerSoLuong = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        lblBan = new javax.swing.JLabel();
        txttimkiem = new JavaSwingThuVien.TextField();
        jPanel7 = new javax.swing.JPanel();
        btnDuavaohoadon = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnXoa1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jpanelban1 = new javax.swing.JPanel();
        lblban1 = new javax.swing.JLabel();
        imgban1 = new javax.swing.JLabel();
        jpanelban2 = new javax.swing.JPanel();
        lblban2 = new javax.swing.JLabel();
        iconban2 = new javax.swing.JLabel();
        jpanelban3 = new javax.swing.JPanel();
        lblban3 = new javax.swing.JLabel();
        iconban3 = new javax.swing.JLabel();
        jpanelban4 = new javax.swing.JPanel();
        lblban4 = new javax.swing.JLabel();
        iconban4 = new javax.swing.JLabel();
        jpanelban5 = new javax.swing.JPanel();
        lblban5 = new javax.swing.JLabel();
        iconban5 = new javax.swing.JLabel();
        jpanelban6 = new javax.swing.JPanel();
        lblban6 = new javax.swing.JLabel();
        iconban6 = new javax.swing.JLabel();
        jpanelban7 = new javax.swing.JPanel();
        lblban7 = new javax.swing.JLabel();
        iconban7 = new javax.swing.JLabel();
        jpanelban8 = new javax.swing.JPanel();
        lblban8 = new javax.swing.JLabel();
        iconban8 = new javax.swing.JLabel();
        jpanelban9 = new javax.swing.JPanel();
        lblban9 = new javax.swing.JLabel();
        iconban9 = new javax.swing.JLabel();
        jpanelban10 = new javax.swing.JPanel();
        lblban10 = new javax.swing.JLabel();
        iconban10 = new javax.swing.JLabel();
        jpanelban11 = new javax.swing.JPanel();
        lblban11 = new javax.swing.JLabel();
        iconban11 = new javax.swing.JLabel();
        jpanelban12 = new javax.swing.JPanel();
        lblban12 = new javax.swing.JLabel();
        iconban12 = new javax.swing.JLabel();
        lblBan14 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        lblBan15 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        lblBan26 = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableHDCT = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelhoadon = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();

        setBorder(null);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        cbxLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxLoai.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Loại: ");

        tableSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã SP", "Tên SP", "Giá", "Mã Loại", "Mô tả", "Hình ảnh"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSanPhamMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableSanPham);

        panelHoaDon.setBackground(new java.awt.Color(255, 255, 255));
        panelHoaDon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtmaHoaDon.setLabelText("Mã Hóa đơn");

        txtmaKH.setLabelText("Mã khách hàng");

        txttenKh.setLabelText("Tên khách hàng");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Mã SP :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Tên SP :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Số lượng :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Giá :");

        lbltenSP.setText("      ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Loại :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("Thành tiền :");

        lblthanhTien.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblthanhTien.setForeground(new java.awt.Color(204, 0, 0));

        txtsdt.setLabelText("Số điện thoại");

        spinnerSoLuong.setModel(new javax.swing.SpinnerNumberModel(1, 1, 20, 1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Bàn:");

        javax.swing.GroupLayout panelHoaDonLayout = new javax.swing.GroupLayout(panelHoaDon);
        panelHoaDon.setLayout(panelHoaDonLayout);
        panelHoaDonLayout.setHorizontalGroup(
            panelHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txttenKh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtmaKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtsdt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelHoaDonLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbltenSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelHoaDonLayout.createSequentialGroup()
                        .addGroup(panelHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelHoaDonLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblmaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelHoaDonLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblthanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelHoaDonLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(spinnerSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelHoaDonLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblGia, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelHoaDonLayout.createSequentialGroup()
                                .addComponent(txtmaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblBan)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelHoaDonLayout.setVerticalGroup(
            panelHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtmaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(lblBan)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttenKh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(panelHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)
                        .addComponent(lblLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblmaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(panelHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbltenSP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(panelHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblGia, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(panelHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(spinnerSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(panelHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblthanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        txttimkiem.setLabelText("Tìm kiếm");
        txttimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimkiemActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        btnDuavaohoadon.setBackground(new java.awt.Color(176, 166, 149));
        btnDuavaohoadon.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnDuavaohoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/addbill.png"))); // NOI18N
        btnDuavaohoadon.setText("THANH TOÁN");
        btnDuavaohoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDuavaohoadonActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(176, 166, 149));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(51, 51, 51));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setPreferredSize(new java.awt.Dimension(90, 31));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnXoa1.setBackground(new java.awt.Color(176, 166, 149));
        btnXoa1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoa1.setForeground(new java.awt.Color(51, 51, 51));
        btnXoa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search_1.png"))); // NOI18N
        btnXoa1.setText("Tìm HD");
        btnXoa1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnXoa1.setPreferredSize(new java.awt.Dimension(90, 31));
        btnXoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDuavaohoadon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(btnXoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnDuavaohoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new java.awt.GridLayout(4, 3, 15, 15));

        jpanelban1.setBackground(new java.awt.Color(193, 244, 197));
        jpanelban1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpanelban1MousePressed(evt);
            }
        });

        lblban1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblban1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblban1.setText("Ban1");

        imgban1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgban1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tablecloth_3.png"))); // NOI18N
        imgban1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jpanelban1Layout = new javax.swing.GroupLayout(jpanelban1);
        jpanelban1.setLayout(jpanelban1Layout);
        jpanelban1Layout.setHorizontalGroup(
            jpanelban1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelban1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpanelban1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imgban1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblban1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jpanelban1Layout.setVerticalGroup(
            jpanelban1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelban1Layout.createSequentialGroup()
                .addComponent(lblban1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imgban1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.add(jpanelban1);

        jpanelban2.setBackground(new java.awt.Color(193, 244, 197));
        jpanelban2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpanelban2MousePressed(evt);
            }
        });

        lblban2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblban2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblban2.setText("Ban2");

        iconban2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconban2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tablecloth_3.png"))); // NOI18N
        iconban2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jpanelban2Layout = new javax.swing.GroupLayout(jpanelban2);
        jpanelban2.setLayout(jpanelban2Layout);
        jpanelban2Layout.setHorizontalGroup(
            jpanelban2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelban2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jpanelban2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblban2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconban2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        jpanelban2Layout.setVerticalGroup(
            jpanelban2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelban2Layout.createSequentialGroup()
                .addComponent(lblban2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconban2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.add(jpanelban2);

        jpanelban3.setBackground(new java.awt.Color(193, 244, 197));
        jpanelban3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpanelban3MousePressed(evt);
            }
        });

        lblban3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblban3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblban3.setText("Ban3");

        iconban3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconban3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tablecloth_3.png"))); // NOI18N
        iconban3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jpanelban3Layout = new javax.swing.GroupLayout(jpanelban3);
        jpanelban3.setLayout(jpanelban3Layout);
        jpanelban3Layout.setHorizontalGroup(
            jpanelban3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelban3Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jpanelban3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblban3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconban3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        jpanelban3Layout.setVerticalGroup(
            jpanelban3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelban3Layout.createSequentialGroup()
                .addComponent(lblban3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconban3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.add(jpanelban3);

        jpanelban4.setBackground(new java.awt.Color(193, 244, 197));
        jpanelban4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpanelban4MousePressed(evt);
            }
        });

        lblban4.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblban4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblban4.setText("Ban4");

        iconban4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconban4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tablecloth_3.png"))); // NOI18N
        iconban4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jpanelban4Layout = new javax.swing.GroupLayout(jpanelban4);
        jpanelban4.setLayout(jpanelban4Layout);
        jpanelban4Layout.setHorizontalGroup(
            jpanelban4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelban4Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jpanelban4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblban4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconban4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        jpanelban4Layout.setVerticalGroup(
            jpanelban4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelban4Layout.createSequentialGroup()
                .addComponent(lblban4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconban4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.add(jpanelban4);

        jpanelban5.setBackground(new java.awt.Color(193, 244, 197));
        jpanelban5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpanelban5MousePressed(evt);
            }
        });

        lblban5.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblban5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblban5.setText("Ban5");

        iconban5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconban5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tablecloth_3.png"))); // NOI18N
        iconban5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jpanelban5Layout = new javax.swing.GroupLayout(jpanelban5);
        jpanelban5.setLayout(jpanelban5Layout);
        jpanelban5Layout.setHorizontalGroup(
            jpanelban5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelban5Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jpanelban5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblban5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconban5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        jpanelban5Layout.setVerticalGroup(
            jpanelban5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelban5Layout.createSequentialGroup()
                .addComponent(lblban5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconban5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.add(jpanelban5);

        jpanelban6.setBackground(new java.awt.Color(193, 244, 197));
        jpanelban6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpanelban6MousePressed(evt);
            }
        });

        lblban6.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblban6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblban6.setText("Ban6");

        iconban6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconban6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tablecloth_3.png"))); // NOI18N
        iconban6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jpanelban6Layout = new javax.swing.GroupLayout(jpanelban6);
        jpanelban6.setLayout(jpanelban6Layout);
        jpanelban6Layout.setHorizontalGroup(
            jpanelban6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelban6Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jpanelban6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblban6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconban6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        jpanelban6Layout.setVerticalGroup(
            jpanelban6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelban6Layout.createSequentialGroup()
                .addComponent(lblban6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconban6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.add(jpanelban6);

        jpanelban7.setBackground(new java.awt.Color(193, 244, 197));
        jpanelban7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpanelban7MousePressed(evt);
            }
        });

        lblban7.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblban7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblban7.setText("Ban7");

        iconban7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconban7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tablecloth_3.png"))); // NOI18N
        iconban7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jpanelban7Layout = new javax.swing.GroupLayout(jpanelban7);
        jpanelban7.setLayout(jpanelban7Layout);
        jpanelban7Layout.setHorizontalGroup(
            jpanelban7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelban7Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jpanelban7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblban7)
                    .addComponent(iconban7))
                .addGap(21, 21, 21))
        );
        jpanelban7Layout.setVerticalGroup(
            jpanelban7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelban7Layout.createSequentialGroup()
                .addComponent(lblban7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconban7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.add(jpanelban7);

        jpanelban8.setBackground(new java.awt.Color(193, 244, 197));
        jpanelban8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpanelban8MousePressed(evt);
            }
        });

        lblban8.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblban8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblban8.setText("Ban8");

        iconban8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconban8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tablecloth_3.png"))); // NOI18N
        iconban8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jpanelban8Layout = new javax.swing.GroupLayout(jpanelban8);
        jpanelban8.setLayout(jpanelban8Layout);
        jpanelban8Layout.setHorizontalGroup(
            jpanelban8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelban8Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jpanelban8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblban8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconban8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        jpanelban8Layout.setVerticalGroup(
            jpanelban8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelban8Layout.createSequentialGroup()
                .addComponent(lblban8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconban8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.add(jpanelban8);

        jpanelban9.setBackground(new java.awt.Color(193, 244, 197));
        jpanelban9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpanelban9MousePressed(evt);
            }
        });

        lblban9.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblban9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblban9.setText("Ban9");

        iconban9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconban9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tablecloth_3.png"))); // NOI18N
        iconban9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jpanelban9Layout = new javax.swing.GroupLayout(jpanelban9);
        jpanelban9.setLayout(jpanelban9Layout);
        jpanelban9Layout.setHorizontalGroup(
            jpanelban9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelban9Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jpanelban9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblban9)
                    .addComponent(iconban9))
                .addGap(20, 20, 20))
        );
        jpanelban9Layout.setVerticalGroup(
            jpanelban9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelban9Layout.createSequentialGroup()
                .addComponent(lblban9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconban9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.add(jpanelban9);

        jpanelban10.setBackground(new java.awt.Color(193, 244, 197));
        jpanelban10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpanelban10MousePressed(evt);
            }
        });

        lblban10.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblban10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblban10.setText("Ban10");

        iconban10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconban10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tablecloth_3.png"))); // NOI18N
        iconban10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jpanelban10Layout = new javax.swing.GroupLayout(jpanelban10);
        jpanelban10.setLayout(jpanelban10Layout);
        jpanelban10Layout.setHorizontalGroup(
            jpanelban10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelban10Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jpanelban10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconban10)
                    .addComponent(lblban10))
                .addGap(15, 15, 15))
        );
        jpanelban10Layout.setVerticalGroup(
            jpanelban10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelban10Layout.createSequentialGroup()
                .addComponent(lblban10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconban10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.add(jpanelban10);

        jpanelban11.setBackground(new java.awt.Color(193, 244, 197));
        jpanelban11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpanelban11MousePressed(evt);
            }
        });

        lblban11.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblban11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblban11.setText("Ban11");

        iconban11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconban11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tablecloth_3.png"))); // NOI18N
        iconban11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jpanelban11Layout = new javax.swing.GroupLayout(jpanelban11);
        jpanelban11.setLayout(jpanelban11Layout);
        jpanelban11Layout.setHorizontalGroup(
            jpanelban11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelban11Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jpanelban11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblban11)
                    .addComponent(iconban11))
                .addGap(14, 14, 14))
        );
        jpanelban11Layout.setVerticalGroup(
            jpanelban11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelban11Layout.createSequentialGroup()
                .addComponent(lblban11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconban11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.add(jpanelban11);

        jpanelban12.setBackground(new java.awt.Color(193, 244, 197));
        jpanelban12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpanelban12MousePressed(evt);
            }
        });

        lblban12.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblban12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblban12.setText("Ban12");

        iconban12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconban12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tablecloth_3.png"))); // NOI18N
        iconban12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jpanelban12Layout = new javax.swing.GroupLayout(jpanelban12);
        jpanelban12.setLayout(jpanelban12Layout);
        jpanelban12Layout.setHorizontalGroup(
            jpanelban12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelban12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpanelban12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblban12)
                    .addComponent(iconban12))
                .addGap(15, 15, 15))
        );
        jpanelban12Layout.setVerticalGroup(
            jpanelban12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelban12Layout.createSequentialGroup()
                .addComponent(lblban12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconban12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.add(jpanelban12);

        lblBan14.setBackground(new java.awt.Color(193, 244, 197));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Ban1");

        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tablecloth_3.png"))); // NOI18N
        jLabel36.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout lblBan14Layout = new javax.swing.GroupLayout(lblBan14);
        lblBan14.setLayout(lblBan14Layout);
        lblBan14Layout.setHorizontalGroup(
            lblBan14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblBan14Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(lblBan14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        lblBan14Layout.setVerticalGroup(
            lblBan14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblBan14Layout.createSequentialGroup()
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.add(lblBan14);

        lblBan15.setBackground(new java.awt.Color(193, 244, 197));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("Ban1");

        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tablecloth_3.png"))); // NOI18N
        jLabel38.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout lblBan15Layout = new javax.swing.GroupLayout(lblBan15);
        lblBan15.setLayout(lblBan15Layout);
        lblBan15Layout.setHorizontalGroup(
            lblBan15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblBan15Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(lblBan15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        lblBan15Layout.setVerticalGroup(
            lblBan15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblBan15Layout.createSequentialGroup()
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.add(lblBan15);

        lblBan26.setBackground(new java.awt.Color(193, 244, 197));

        jLabel59.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel59.setText("Ban1");

        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tablecloth_3.png"))); // NOI18N
        jLabel60.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout lblBan26Layout = new javax.swing.GroupLayout(lblBan26);
        lblBan26.setLayout(lblBan26Layout);
        lblBan26Layout.setHorizontalGroup(
            lblBan26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblBan26Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(lblBan26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel59, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel60, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        lblBan26Layout.setVerticalGroup(
            lblBan26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblBan26Layout.createSequentialGroup()
                .addComponent(jLabel59)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.add(lblBan26);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        tableHDCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã HDCT", "Mã HD", "MaSP", "TenSP", "SoLuong", "GiaTien"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tableHDCT);

        jTabbedPane1.addTab("HDCT", jScrollPane4);

        tabelhoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã HD", "Mã KH", "Mã NV", "NgayDatHang", "Mã bàn", "Thành tiền", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelhoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelhoadonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelhoadon);

        jTabbedPane1.addTab("Hóa đơn chờ thanh toán", jScrollPane1);

        jButton2.setBackground(new java.awt.Color(176, 166, 149));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton2.setText("TẠO HÓA ĐƠN MỚI");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(176, 166, 149));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Add Shopping Cart.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnMoi.setBackground(new java.awt.Color(176, 166, 149));
        btnMoi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMoi.setForeground(new java.awt.Color(51, 51, 51));
        btnMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New.png"))); // NOI18N
        btnMoi.setText("Mới");
        btnMoi.setPreferredSize(new java.awt.Dimension(90, 31));
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panelHoaDon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(0, 30, Short.MAX_VALUE)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbxLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14)))
                        .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(panelHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0)
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 982, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 654, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSanPhamMouseClicked
        if (evt.getClickCount() == 1) {
            this.row = tableSanPham.getSelectedRow();
            this.edit();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tableSanPhamMouseClicked

    private void txttimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimkiemActionPerformed
        filltableSanPham();
        // TODO add your handling code here:
    }//GEN-LAST:event_txttimkiemActionPerformed

    private void btnDuavaohoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuavaohoadonActionPerformed
        updateDuaVaohoadon();
        Menu menu = new Menu();
        menu.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDuavaohoadonActionPerformed

    private void btnXoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa1ActionPerformed
        fillTableHDCT();
        TinhTien();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoa1ActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        lblBan.setText("");
        Moi();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        deleteChitiethoadon();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        InsertHoadonchitiet();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        InsertHoaDon();
        //  trangthaiban();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tabelhoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelhoadonMouseClicked
        if (evt.getClickCount() == 2) {
            this.row = tabelhoadon.getSelectedRow();
            String maban = (String) tabelhoadon.getValueAt(row, 4);
            selectBanchuathanhtoan(maban);
            fillTableHDCT();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelhoadonMouseClicked

    private void jpanelban1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelban1MousePressed
        String giatri = lblban1.getText();
        lblBan.setText(giatri);
        Moi();
        newSP();
        selectBanchuathanhtoan(lblBan.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_jpanelban1MousePressed

    private void jpanelban2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelban2MousePressed
        String giatri = lblban2.getText();
        lblBan.setText(giatri);
        Moi();
        newSP();
        selectBanchuathanhtoan(lblBan.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_jpanelban2MousePressed

    private void jpanelban3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelban3MousePressed
        String giatri = lblban3.getText();
        lblBan.setText(giatri);
        Moi();
        newSP();
        selectBanchuathanhtoan(lblBan.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_jpanelban3MousePressed

    private void jpanelban4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelban4MousePressed
        String giatri = lblban4.getText();
        lblBan.setText(giatri);
        Moi();
        newSP();
        selectBanchuathanhtoan(lblBan.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_jpanelban4MousePressed

    private void jpanelban5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelban5MousePressed
        String giatri = lblban5.getText();
        lblBan.setText(giatri);
        Moi();
        newSP();
        selectBanchuathanhtoan(lblBan.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_jpanelban5MousePressed

    private void jpanelban6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelban6MousePressed
        String giatri = lblban6.getText();
        lblBan.setText(giatri);
        Moi();
        newSP();
        selectBanchuathanhtoan(lblBan.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_jpanelban6MousePressed

    private void jpanelban7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelban7MousePressed
        String giatri = lblban7.getText();
        lblBan.setText(giatri);
        Moi();
        newSP();
        selectBanchuathanhtoan(lblBan.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_jpanelban7MousePressed

    private void jpanelban8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelban8MousePressed

        String giatri = lblban8.getText();
        lblBan.setText(giatri);
        Moi();
        newSP();
        selectBanchuathanhtoan(lblBan.getText());// TODO add your handling code here:
    }//GEN-LAST:event_jpanelban8MousePressed

    private void jpanelban9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelban9MousePressed
        String giatri = lblban9.getText();
        lblBan.setText(giatri);
        Moi();
        newSP();
        selectBanchuathanhtoan(lblBan.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_jpanelban9MousePressed

    private void jpanelban10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelban10MousePressed
        String giatri = lblban10.getText();
        lblBan.setText(giatri);
        Moi();
        newSP();
        selectBanchuathanhtoan(lblBan.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_jpanelban10MousePressed

    private void jpanelban11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelban11MousePressed
        String giatri = lblban11.getText();
        lblBan.setText(giatri);
        Moi();
        newSP();
        selectBanchuathanhtoan(lblBan.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_jpanelban11MousePressed

    private void jpanelban12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelban12MousePressed
        String giatri = lblban12.getText();
        lblBan.setText(giatri);
        Moi();
        newSP();
        selectBanchuathanhtoan(lblBan.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_jpanelban12MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDuavaohoadon;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoa1;
    private javax.swing.JComboBox<String> cbxLoai;
    private javax.swing.JLabel iconban10;
    private javax.swing.JLabel iconban11;
    private javax.swing.JLabel iconban12;
    private javax.swing.JLabel iconban2;
    private javax.swing.JLabel iconban3;
    private javax.swing.JLabel iconban4;
    private javax.swing.JLabel iconban5;
    private javax.swing.JLabel iconban6;
    private javax.swing.JLabel iconban7;
    private javax.swing.JLabel iconban8;
    private javax.swing.JLabel iconban9;
    private javax.swing.JLabel imgban1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jpanelban1;
    private javax.swing.JPanel jpanelban10;
    private javax.swing.JPanel jpanelban11;
    private javax.swing.JPanel jpanelban12;
    private javax.swing.JPanel jpanelban2;
    private javax.swing.JPanel jpanelban3;
    private javax.swing.JPanel jpanelban4;
    private javax.swing.JPanel jpanelban5;
    private javax.swing.JPanel jpanelban6;
    private javax.swing.JPanel jpanelban7;
    private javax.swing.JPanel jpanelban8;
    private javax.swing.JPanel jpanelban9;
    private javax.swing.JLabel lblBan;
    private javax.swing.JPanel lblBan14;
    private javax.swing.JPanel lblBan15;
    private javax.swing.JPanel lblBan26;
    private javax.swing.JLabel lblGia;
    private javax.swing.JLabel lblLoai;
    private javax.swing.JLabel lblban1;
    private javax.swing.JLabel lblban10;
    private javax.swing.JLabel lblban11;
    private javax.swing.JLabel lblban12;
    private javax.swing.JLabel lblban2;
    private javax.swing.JLabel lblban3;
    private javax.swing.JLabel lblban4;
    private javax.swing.JLabel lblban5;
    private javax.swing.JLabel lblban6;
    private javax.swing.JLabel lblban7;
    private javax.swing.JLabel lblban8;
    private javax.swing.JLabel lblban9;
    private javax.swing.JLabel lblmaSP;
    private javax.swing.JLabel lbltenSP;
    private javax.swing.JLabel lblthanhTien;
    private javax.swing.JPanel panelHoaDon;
    private javax.swing.JSpinner spinnerSoLuong;
    private javax.swing.JTable tabelhoadon;
    private javax.swing.JTable tableHDCT;
    private javax.swing.JTable tableSanPham;
    private JavaSwingThuVien.TextField txtmaHoaDon;
    private JavaSwingThuVien.TextField txtmaKH;
    private JavaSwingThuVien.TextField txtsdt;
    private JavaSwingThuVien.TextField txttenKh;
    private JavaSwingThuVien.TextField txttimkiem;
    // End of variables declaration//GEN-END:variables
//    void fillcomboBoxBan() {
//        DefaultComboBoxModel model = (DefaultComboBoxModel) cbxMaBan.getModel();
//        model.removeAllElements();
//        List<Ban> list = daoBan.selectAll();
//        for (Ban kh : list) {
//            model.addElement(kh);
//        }
//    }

    void filltableSanPham() {
        MyQuery mq = new MyQuery();
        String keyword = txttimkiem.getText();
        ArrayList<Product2> list = mq.selectByKeyword(keyword);
        String[] columnName = {"MaSP", "TenSP", "Gia", "MaLoai", "MoTa", "HinhAnh"};
        Object[][] rows = new Object[list.size()][6];
        for (int i = 0; i < list.size(); i++) {
            rows[i][0] = list.get(i).getMaSP();
            rows[i][1] = list.get(i).getTenSP();
            rows[i][2] = list.get(i).getGia();
            rows[i][3] = list.get(i).getMaLoai();
            rows[i][4] = list.get(i).getMoTa();
            if (list.get(i).getHinhanh() != null) {
                ImageIcon image = new ImageIcon(new ImageIcon(list.get(i).getHinhanh()).getImage().getScaledInstance(100, 70, Image.SCALE_SMOOTH));
                rows[i][5] = image;
            } else {
                rows[i][5] = null;
            }
        }
        TheModel model = new TheModel(rows, columnName);
        tableSanPham.setModel(model);
        tableSanPham.setRowHeight(70);
        tableSanPham.getColumnModel().getColumn(5).setPreferredWidth(100);
    }

    void fillTableHDCT() {
//        if (txtmaHoaDon.getText().equals("")) {
//            DialogHelper.alert(this, "Bàn này không có hóa đơn đang chờ");
//        }
        DefaultTableModel model = (DefaultTableModel) tableHDCT.getModel();
        model.setRowCount(0);
        try {
            String mahd = txtmaHoaDon.getText();
            List<ChiTietHoaDon> list = daohdct.selectMaHD(mahd);
            for (ChiTietHoaDon hdct : list) {
                Object[] row = {hdct.getHoaDonCT(), hdct.getMaHD(), hdct.getMaSP(), hdct.getTenSP(), hdct.getSoLuong(), hdct.getGiaTien()};
                model.addRow(row);
            }
        } catch (Exception e) {
            System.out.println("lỗi filltable hdct: " + e);
        }
    }

    public void fillcomboboxLoai() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbxLoai.getModel();
        model.removeAllElements();
        List<Loai> list = daoloai.selectAll();
        for (Loai kh : list) {
            model.addElement(kh);
        }
    }

    void OpenMenu() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i < width; i++) {
                    panelHoaDon.setSize(i, height);
                    try {
                        Thread.sleep(1);
                    } catch (Exception e) {
                    }
                }
            }
        }).start();
    }

    void CloseMenu() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = width - 1; i > 0; i--) {
                    panelHoaDon.setSize(i, height);
                    try {
                        Thread.sleep(1);
                    } catch (Exception e) {
                    }

                }
            }
        }).start();
    }

    public void setForm(SanPham sp) {
        lblGia.setText(String.valueOf(sp.getGia()));
        lblLoai.setText(sp.getMaLoai());
        lblmaSP.setText(sp.getMaSP());
        lbltenSP.setText(sp.getTenSP());
    }

    public void setForm(HoaDon hd, KhachHang kh) {
        txtmaHoaDon.setText(hd.getMaHD());
        txtmaKH.setText(hd.getMaKH());
        txttenKh.setText(kh.getMaKH());
        txtsdt.setText(kh.getSDT());
    }

    public HoaDon getFormHoaDon() {
        HoaDon hd = new HoaDon();
        hd.setMaHD(txtmaHoaDon.getText());
        hd.setMaKH(txtmaKH.getText());
        hd.setMaBan(lblBan.getText());
        hd.setMaNV(Auth.user.getMaNV());
        Date Ngaychuyendoi = Date.from(ngay.atStartOfDay().atZone(ZoneId.systemDefault()).toInstant());
        hd.setNgayDatHang(Ngaychuyendoi);
        hd.setThanhTien(0);
        hd.setTrangThai(false);
        return hd;
    }

    public KhachHang getFormKhachHang() {
        KhachHang kh = new KhachHang();
        kh.setMaKH(txtmaKH.getText());
        kh.setTenKH(txttenKh.getText());
        kh.setSDT(txtsdt.getText());
        kh.setMaban(lblBan.getText());
        return kh;
    }

    public ChiTietHoaDon getFormCTHD() {
        ChiTietHoaDon cthd = new ChiTietHoaDon();
        cthd.setMaHD(txtmaHoaDon.getText());
        cthd.setMaSP(lblmaSP.getText());
        cthd.setTenSP(lbltenSP.getText());
        cthd.setSoLuong((int) spinnerSoLuong.getValue());
        cthd.setGiaTien(Float.parseFloat(lblGia.getText()));
        return cthd;
    }

    public void InsertKhachang() {
        KhachHang kh = getFormKhachHang();
        try {
            daokh.insert(kh);
            filltableSanPham();
            //   fillcomboBoxBan();
            fillcomboboxLoai();
            System.out.println("insert khách hàng thành công");
        } catch (Exception e) {
            DialogHelper.alert(this, "Lỗi khách hàng khi tạo hóa đơn");
            System.out.println(e);
        }
    }

    public void InsertHoaDon() {
        if (KiemThu() == false) {
            return;
        }

        HoaDon hd = getFormHoaDon();
        try {
            InsertKhachang();
            daohd.insert(hd);
            fillTableHDCT();
            filltableSanPham();
            //fillcomboBoxBan();
            fillcomboboxLoai();
            TinhTien();
            setEnabled();
            selectBanchuathanhtoan(lblBan.getText());
            trangthaiban(lblBan.getText());
            DialogHelper.alert(this, "Tạo hóa đơn thành công");
        } catch (Exception e) {
            DialogHelper.alert(this, "Tạo hóa đơn thất bại");
            System.out.println(e);
        }
    }

    public void InsertHoadonchitiet() {
        String mahd = txtmaHoaDon.getText();
        String masp = lblmaSP.getText();
        int soluong1 = (int) spinnerSoLuong.getValue();
        if (KiemthuinsertHDCT() == false) {
            return;
        }
        ChiTietHoaDon hdct = getFormCTHD();
        try {
            int tongsoluong;
            List<ChiTietHoaDon> list = daohdct.selectMaHD(mahd);
            for (ChiTietHoaDon chiTietHoaDon : list) {
                System.out.println("đã chạy đến đây" + list);
                if (chiTietHoaDon.getMaSP().equals(masp) == true) {
                    int soluong = chiTietHoaDon.getSoLuong();
                    tongsoluong = soluong + soluong1;
                    System.out.println("masp: " + chiTietHoaDon.getMaSP().equals(lblmaSP.getText()));
                    System.out.println("so luong; " + soluong);
                    daohdct.updateSoluong(tongsoluong, masp);
//                for (int i = 0; i < rowcout; i++) {
//                    Object masp = tableHDCT.getValueAt(i, 3);
//                    //tongsoluong = soluong + Integer.parseInt((String) spinnerSoLuong.getValue());
//                    if (chiTietHoaDon.getMaSP().equals(masp)) {
////                        List<ChiTietHoaDon> soluong = daohdct.selectSoLuong((String) masp);
////                        hdct.setSoLuong(tongsoluong);
//                        daohdct.updateSoluong((String) masp,tongsoluong);
                } else {
                    daohdct.insert(hdct);
                }
            }
            fillTableHDCT();
            spinnerSoLuong.setValue(1);
            //   fillcomboBoxBan();
            filltableSanPham();
            TinhTien();
            System.out.println("thêm thành công");
        } catch (Exception e) {
            DialogHelper.alert(this, "Insert lỗi");
            System.out.println(e);
        }
    }

    public void deleteChitiethoadon() {
        try {
            int[] rows = tableHDCT.getSelectedRows();
            if (rows.length == 0) {
                DialogHelper.alert(this, "Bạn cần chọn sản phẩm để xóa !");
                return;
            }
            if (rows.length > 0 && DialogHelper.confirm(this, "Bạn có muốn xóa sản phẩm này không?")) {
                for (int row : rows) {
                    int makh = (int) tableHDCT.getValueAt(row, 0);
                    daohdct.delete(makh);
                    DialogHelper.alert(this, "Xóa sản phẩm thành công");
                    fillTableHDCT();
                    filltableSanPham();
                    TinhTien();
                }
            }
        } catch (Exception e) {
            DialogHelper.alert(this, "Lỗi khi xóa sản phẩm");
            System.out.println(e);
        }
    }

    public void edit() {
        String maSp = (String) tableSanPham.getValueAt(row, 0);
        SanPham sp = daosp.selectById(maSp);
        this.setForm(sp);
    }

    public void TinhTien() {
        int tong = 0;
        int rowcout = tableHDCT.getRowCount();
        for (int i = 0; i < rowcout; i++) {
            Object gia = tableHDCT.getValueAt(i, 5);
            tong += ((Number) gia).intValue();
        }
        System.out.println(tong);
        lblthanhTien.setText(String.valueOf(tong));
    }

    void updateDuaVaohoadon() {
        String mahd = txtmaHoaDon.getText();
        if (mahd.equals("")) {
            DialogHelper.alert(this, "Bạn cần tạo hóa đơn");
        }
        float thanhtien = Float.parseFloat(lblthanhTien.getText());
        try {
//            List<HoaDon> list = daohd.UpdateThanhTienhoadon(mahd, thanhtien);
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=DuanCoffee";
            Connection con = DriverManager.getConnection(url, "sa", "123456");
            String sql = "update HoaDon set ThanhTien = ? ,trangthai = 1 where MaHD = ?";
            PreparedStatement pstt = con.prepareStatement(sql);
            pstt.setFloat(1, Float.parseFloat(lblthanhTien.getText()));
            pstt.setString(2, txtmaHoaDon.getText());
            pstt.executeUpdate();
            DialogHelper.alert(this, "Đưa vào hóa đơn thành công");
////            String giatri = lblban2.getText();
////            lblBan.setText(giatri);
            String maban = lblBan.getText();
            trangthaiban1(maban);
            Moi();
            selectBanchuathanhtoan(maban);
            con.close();
        } catch (Exception e) {
            DialogHelper.alert(this, "lỖI ĐƯA VÒA HĐ");
            System.out.println(e);
        }
    }

    void setEnabled() {
        txtmaHoaDon.setEnabled(false);
        txtmaKH.setEnabled(false);
        txtsdt.setEnabled(false);
        txttenKh.setEnabled(false);
    }

    void Moi() {
        txtmaHoaDon.setEnabled(true);
        txtmaKH.setEnabled(true);
        txtsdt.setEnabled(true);
        txttenKh.setEnabled(true);
        txtmaHoaDon.setText("");
        txtmaKH.setText("");
        txtsdt.setText("");
        txttenKh.setText("");
        System.out.println(ngay);
        newSP();
        DefaultTableModel model = (DefaultTableModel) tableHDCT.getModel();
        model.setRowCount(0);
//        DefaultTableModel model1 = (DefaultTableModel) tabelhoadon.getModel();
//        model1.setRowCount(0);
    }

    void newSP() {
        lblthanhTien.setText("0");
        lblGia.setText("");
        lblmaSP.setText("");
        lbltenSP.setText("");
        lblLoai.setText("");
        spinnerSoLuong.setValue(1);
        DefaultTableModel model = (DefaultTableModel) tableHDCT.getModel();
        model.setRowCount(0);
    }

    boolean KiemthuinsertHDCT() {
        if (txtmaHoaDon.getText().equals("")) {
            DialogHelper.alert(this, "Bạn cần chọn hóa đơn để thêm sản phẩm !");
            return false;
        }
        if (lbltenSP.getText().equals("")) {
            DialogHelper.alert(this, "Bạn cần chọn sản phẩm để thêm");
            return false;
        }
        return true;
    }

    boolean KiemThu() {
        if (txtmaHoaDon.getText().equals("")) {
            DialogHelper.alert(this, "Không được bỏ trống Mã hóa đơn");
            return false;
        }
        if (txtmaKH.getText().equals("")) {
            DialogHelper.alert(this, "Không được bỏ trống mã khách hàng");
            return false;
        }
        if (txtsdt.getText().equals("")) {
            DialogHelper.alert(this, "Không được bỏ trống SDT");
            return false;
        }
        if (txttenKh.getText().length() < 3) {
            DialogHelper.alert(this, "Không được bỏ trống Tên khách hàng");
            return false;
        }
        if (lblBan.getText().equalsIgnoreCase("")) {
            DialogHelper.alert(this, "Vui lòng chọn bàn!");
            return false;
        }
        List<KhachHang> list = daokh.selectAll();
        for (KhachHang kh : list) {
            if (txtmaKH.getText().equalsIgnoreCase(kh.getMaKH())) {
                DialogHelper.alert(this, "Mã khách hàng đã có!");
                return false;
            }
        }
        List<HoaDon> listhd = daohd.selectAll();
        for (HoaDon hoaDon : listhd) {
            if (txtmaHoaDon.getText().equalsIgnoreCase(hoaDon.getMaHD())) {
                DialogHelper.alert(this, "Mã hóa đơn đã có!");
                return false;
            }
        }
        return true;
    }

    public void getban(String maban) {
        try {
            try {
                ResultSet rs = null;
                try {
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    String url = "jdbc:sqlserver://localhost:1433;databaseName=DuanCoffee";
                    Connection con = DriverManager.getConnection(url, "sa", "123456");
                    String sql = "select MaHD,khachhang.MaKH,TenKH,SDT from hoadon inner join KhachHang on HoaDon.MaKH = KhachHang.MaKH where KhachHang.MaBan = ?";
                    rs = JdbcHelper.executeQuery(sql, maban);
                    while (rs.next()) {
                        txtmaHoaDon.setText(rs.getString("Mahd"));
                        txtmaKH.setText(rs.getString("MaKH"));
                        txttenKh.setText(rs.getString("TenKH"));
                        txtsdt.setText(rs.getString("SDT"));
                    }
                } finally {
                    rs.getStatement().getConnection().close();
                }
            } catch (SQLException e) {
                throw new RuntimeException(e);
            }
        } catch (Exception e) {
        }
    }

    void selectBanchuathanhtoan(String maban) {
        try {
            try {
                ResultSet rs = null;
                try {
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    String url = "jdbc:sqlserver://localhost:1433;databaseName=DuanCoffee";
                    Connection con = DriverManager.getConnection(url, "sa", "123456");
                    String sql = "select MaHD,khachhang.MaKH,TenKH,SDT from hoadon inner join KhachHang on HoaDon.MaKH = KhachHang.MaKH where KhachHang.MaBan = ? and trangthai =0";
                    rs = JdbcHelper.executeQuery(sql, maban);
                    while (rs.next()) {
                        txtmaHoaDon.setText(rs.getString("Mahd"));
                        txtmaKH.setText(rs.getString("MaKH"));
                        txttenKh.setText(rs.getString("TenKH"));
                        txtsdt.setText(rs.getString("SDT"));
                    }
                } finally {
                    rs.getStatement().getConnection().close();
                }
            } catch (SQLException e) {
                throw new RuntimeException(e);
            }
            filltableHoaDon();
            fillTableHDCT();
            TinhTien();
            //  setEnabled();
        } catch (Exception e) {
        }
    }

    public void filltableHoaDon() {
        DefaultTableModel model = (DefaultTableModel) tabelhoadon.getModel();
        model.setRowCount(0);
        try {
            String maban = lblBan.getText();
            List<HoaDon> list = daohd.selecthoadonBan();
            for (HoaDon hoaDon : list) {
                Object[] row = {hoaDon.getMaHD(), hoaDon.getMaKH(), hoaDon.getMaNV(), XDate.toString(hoaDon.getNgayDatHang(), "dd-MM-YYYY"), hoaDon.getMaBan(), hoaDon.getThanhTien(), hoaDon.getTrangThai() ? "Đã Thanh toán" : "Chưa thanh toán"};
                model.addRow(row);
                if (hoaDon.getTrangThai() == false) {
                    //System.out.println("mabanlaytutrangthai: " + hoaDon.getMaBan());
                    String banchuathanhtoan = hoaDon.getMaBan();
                    trangthaiban(banchuathanhtoan);
                    System.out.println("-- : " + banchuathanhtoan);
                }
//                if (hoaDon.getTrangThai() == true) {
//                    String bandathanhtoan = hoaDon.getMaBan();
//                    trangthaiban1(bandathanhtoan);
//                    System.out.println("bandathanhtoan: ");
//                }
            }
        } catch (Exception e) {
            DialogHelper.alert(this, "Lỗi filltable Hóa đơn");
            System.out.println(e);
        }
    }

    void fillhoadonchuathanhtoan() {

    }

    void trangthaiban(String banchuathanhtoan) {
        // String ban = lblBan.getText();
        if (lblban1.getText().equalsIgnoreCase(banchuathanhtoan)) {
            jpanelban1.setBackground(red);
        }
        if (lblban2.getText().equalsIgnoreCase(banchuathanhtoan)) {
            jpanelban2.setBackground(red);
        }

        if (lblban3.getText().equalsIgnoreCase(banchuathanhtoan)) {
            jpanelban3.setBackground(red);
        }

        if (lblban4.getText().equalsIgnoreCase(banchuathanhtoan)) {
            jpanelban4.setBackground(red);
        }

        if (lblban5.getText().equalsIgnoreCase(banchuathanhtoan)) {
            jpanelban5.setBackground(red);
        }

        if (lblban6.getText().equalsIgnoreCase(banchuathanhtoan)) {
            jpanelban6.setBackground(red);
        }

        if (lblban7.getText().equalsIgnoreCase(banchuathanhtoan)) {
            jpanelban7.setBackground(red);
        }

        if (lblban8.getText().equalsIgnoreCase(banchuathanhtoan)) {
            jpanelban8.setBackground(red);
        }

        if (lblban9.getText().equalsIgnoreCase(banchuathanhtoan)) {
            jpanelban9.setBackground(red);
        }

        if (lblban10.getText().equalsIgnoreCase(banchuathanhtoan)) {
            jpanelban10.setBackground(red);
        }

        if (lblban11.getText().equalsIgnoreCase(banchuathanhtoan)) {
            jpanelban11.setBackground(red);
        }

        if (lblban12.getText().equalsIgnoreCase(banchuathanhtoan)) {
            jpanelban12.setBackground(red);
        }

    }

    void trangthaiban1(String banchuathanhtoan) {
        // String ban = lblBan.getText();
        if (lblban1.getText().equalsIgnoreCase(banchuathanhtoan)) {
            jpanelban1.setBackground(white);
        }

        if (lblban2.getText().equalsIgnoreCase(banchuathanhtoan)) {
            jpanelban2.setBackground(white);
        }

        if (lblban3.getText().equalsIgnoreCase(banchuathanhtoan)) {
            jpanelban3.setBackground(white);
        }

        if (lblban4.getText().equalsIgnoreCase(banchuathanhtoan)) {
            jpanelban4.setBackground(white);
        }

        if (lblban5.getText().equalsIgnoreCase(banchuathanhtoan)) {
            jpanelban5.setBackground(white);
        }

        if (lblban6.getText().equalsIgnoreCase(banchuathanhtoan)) {
            jpanelban6.setBackground(white);
        }

        if (lblban7.getText().equalsIgnoreCase(banchuathanhtoan)) {
            jpanelban7.setBackground(white);
        }

        if (lblban8.getText().equalsIgnoreCase(banchuathanhtoan)) {
            jpanelban8.setBackground(white);
        }

        if (lblban9.getText().equalsIgnoreCase(banchuathanhtoan)) {
            jpanelban9.setBackground(white);
        }

        if (lblban10.getText().equalsIgnoreCase(banchuathanhtoan)) {
            jpanelban10.setBackground(white);
        }

        if (lblban11.getText().equalsIgnoreCase(banchuathanhtoan)) {
            jpanelban11.setBackground(white);
        }

        if (lblban12.getText().equalsIgnoreCase(banchuathanhtoan)) {
            jpanelban12.setBackground(white);
        }

    }

//    void upadtethanhtien() {
//        String mahd = txtmaHoaDon.getText();
//        int thanhtien = Integer.parseInt(lblthanhTien.getText());
//        try {
//            List<HoaDon> list = daohd.updateDuaVaohoadon(mahd, thanhtien);
//        } catch (Exception e) {
//            DialogHelper.alert(this, "Lỗi khi đưa vào hóa đơn");
//            System.out.println(e);
//        }
//    }
}
